"""updates to publication model

Revision ID: 2cd466a54e5f
Revises: e2cee747dae4
Create Date: 2025-02-05 12:00:08.774084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd466a54e5f'
down_revision: Union[str, None] = 'e2cee747dae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_course_teaching_id', table_name='courses')
    op.drop_table('courses')
    op.drop_index('idx_publication_user_id', table_name='publications')
    op.drop_table('publications')
    op.drop_index('idx_teaching_user_id', table_name='teaching_experiences')
    op.drop_table('teaching_experiences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_experiences',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('teaching_experiences_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('institution', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_teaching_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='teaching_experiences_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_teaching_user_id', 'teaching_experiences', ['user_id'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('abstract', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('authors', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('publication_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('journal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pdf_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_publication_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='publications_pkey')
    )
    op.create_index('idx_publication_user_id', 'publications', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teaching_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teaching_id'], ['teaching_experiences.id'], name='fk_course_teaching_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='courses_pkey')
    )
    op.create_index('idx_course_teaching_id', 'courses', ['teaching_id'], unique=False)
    # ### end Alembic commands ###
